config/routes.rb
Rails.application.routes.draw do

  root to: "inicio#index"
   get "login", to: "login#new"
   post "login", to: "login#create"
   get "newinteressado", to: "users#newinteressado"
   get "newestudante", to: "users#newestudante"
   get "newinvestidor", to: "users#newinvestidor"
   get "newcompany", to: "users#newcompany"
   resources :users, only: [:newcompany, :create] 
   resources :categories, only: [:new, :create, :edit, :update, :edit, :update]
   get"/categories/:id" => "categories#destroy"
   get "categorias/index", to: "categories#index"
   get "produtos/index", to: "produtos#index"
   get '/solucoes/:id', to: 'solucoes#show' , as: 'solucoe'
   resources :produtos, only: [:new, :create, :edit, :update]
   get "produtos/index", to: "produtos#index"
   get"/produtos/:id" => "produtos#destroy"
   resources :marcas, only: [:new, :create, :edit, :update]
   get "marcas/index", to: "marcas#index"
   get"/marcas/:id" => "marcas#destroy"
   get "/home", to: "home#index"
   resources :grupos, only: [:new, :create, :edit, :update, :edit, :update]
   get "grupos/index", to: "grupos#index"
   get"/grupos/:id" => "grupos#destroy"
 
   get "subgrupos/index", to: "subgrupos#index"
   resources :subgrupos, only: [:new, :create, :edit, :update]
   get"/subgrupos/:id" => "subgrupos#destroy"
   get "parceiros/index", to: "parceiros#index"
   resources :parceiros, only: [:new, :create, :edit, :update]
   get"/parceiros/:id" => "parceiros#destroy"
   get "financeiro/index", to: "financeiros#index"
   resources :financeiros, only: [:new, :create, :edit, :update]
   get"/financeiro/:id" => "financeiros#destroy"
   get "inicio", to: "inicio#index"
   get "solucoes", to: "solucoes#index"
   get "viewprodutos", to: "solucoes#produtos"
   get "palavras/index", to: "palavras_chaves#index" 
   resources :palavras_chaves, only: [:new, :create, :edit, :update]
   get "palavras_chaves/:id" => "palavras_chaves#destroy"
   get "plataformas/index", to: "plataformas#index" 
   resources :plataformas, only: [:new, :create, :edit, :update]
   get "plataformas/:id" => "plataformas#destroy"
   get "tiposprojetos/index", to: "tipo_projetos#index" 
   resources :tipo_projetos, only: [:new, :create, :edit, :update]
   get"/tipo_projetos/:id" => "tipo_projetos#destroy"
   get '/produtoschaves/:id', to: 'produto_chaves#show' , as: 'produtochaves'
    get '/produtoschaves/:produto_id', to: 'produtos#associacao' , as: 'associacao'
   resources :produto_chaves, only: [:new,  :create, :edit, :update]
 
   resources :visitantes, only: [:new, :create]
  resources :parceiro_produtos
   get "interesse/index", to: "parceiro_produtos#index"
   get "interesse/new", to: "parceiro_produtos#interesse" 
   get "interesse/adicionarinteresse", to: "parceiro_produtos#adicionarinteresse" 
   get '/interesses/:id', to: 'parceiro_produtos#produto' , as: 'interesse'
  get "visitantes/login", to: "loginvisitantes#new"
 post "visitantes/login", to: "loginvisitantes#create"
   resources :contatos
  resources :emails
   resources :visitanteinteressados
     resources :perfils, only: [:new,  :create, :edit, :update]
  resources :enderecos
    get "perfil/index", to: "perfils#index"
      get "ideia/index", to: "ideia#index" 
   get "ideia/suasideias", to: "ideia#suasideias" 
   get "ideium/:id", to: 'ideia#show', as: 'interessou'
    get "suaideia/:id", to: 'ideia#suaideiashow', as: 'suaideia'
   resources :ideia, only: [:new, :create, :edit, :update]
   get"/ideia/:id" => "ideia#destroy"
    
    resources :useradmin, only: [:new, :create, :edit, :update]
    get 'useradmin/index', to: "useradmin#index"
    resources :modulos, only: [:new, :create, :edit, :update]
    get 'modulos/index', to: "modulos#index"

  resources :motivos, only: [:new, :create, :edit, :update]
  get 'motivos/index', to: "motivos#index"
  resources :agendas, only: [:new, :create, :edit, :update]
  get 'agendas/index', to: "agendas#index"
  resources :statuses, only: [:new, :create, :edit, :update]
  
  resources :tipos, only: [:new, :create, :edit, :update]
  resources :empresas, only: [:new, :create, :edit, :update]
  get 'empresa/index', to: "empresas#index"

 

end

app/models/motivo.rb
class Motivo < ActiveRecord::Base
    belongs_to :user
    has_many :agendas
end

app/controllers/motivos_controller.rb
class MotivosController < ApplicationController
   before_filter :authorize_user, only: [:show, :edit, :update, :destroy, :index]

  # GET /motivos
  # GET /motivos.json
  def index
    @motivos = current_user.motivos
  end

  # GET /motivos/1
  # GET /motivos/1.json
  def show
        @motivo = current_user.motivos.find(params[:id])
  end

  # GET /motivos/new
  def new
    @motivo = current_user.motivos.build
  end

  # GET /motivos/1/edit
  def edit
            @motivo = current_user.motivos.find(params[:id])
  end

  # POST /motivos
  # POST /motivos.json
  def create
    @motivo = current_user.motivos.build(motivo_params)

    respond_to do |format|
      if @motivo.save
        format.html { redirect_to motivos_index_path, notice: 'Motivo was successfully created.' }
        format.json { render :show, status: :created, location: @motivo }
      else
        format.html { render :new }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motivos/1
  # PATCH/PUT /motivos/1.json
  def update
            @motivo = current_user.motivos.find(params[:id])
    respond_to do |format|
      if @motivo.update(motivo_params)
        format.html { redirect_to motivos_index_path, notice: 'Motivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @motivo }
      else
        format.html { render :edit }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motivos/1
  # DELETE /motivos/1.json
  def destroy
            @motivo = current_user.motivos.find(params[:id])
    @motivo.destroy
    respond_to do |format|
      format.html { redirect_to motivos_index_path, notice: 'Motivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motivo
      @motivo = Motivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motivo_params
      params.require(:motivo).permit(:descricao)
    end
      def authorize_user
      unless current_user
        redirect_to root_path, alert:"You need to login to continue."
      end
    end
end

app/helpers/motivos_helper.rb
module MotivosHelper
end

app/views/motivos/_form.html.erb
<%= form_for(@motivo, html: { class: 'form-horizontal' }) do |f| %>
    <div class="row">
        <% if @motivo.errors.any? %>
            <div class="alert alert-error">
                <h3>
                    <%= pluralize(@motivo.errors.count, "error") %> prohibited this job from being saved:</h3>

                <ul>
                    <% @motivo.errors.full_messages.each do |msg| %>
                        <li>
                            <%= msg %>
                        </li>
                        <% end %>
                </ul>
            </div>
            <% end %>

                <div class="control-group">
                    <%= f.label :descricao, class: 'control-label' %>
                        <div class="controls">
                            <%= f.text_field :descricao%>
                        </div>
                </div>
                <div class="control-group controls">
                    <%= f.submit class: 'btn btn-primary' %>
                </div>
    </div>
    <% end %>

app/views/motivos/edit.html.erb
<section class="content-header">
    <h1>Editar Motivo</h1>
    <ol class="breadcrumb">
        <a class="btn btn-app" href="<%= motivos_index_path %>">
            <i class="fa fa-reply"></i> Voltar
        </a>
    </ol>
</section>
<section class="content">
    <div class="container">
        <%= render "form" %>
    </div>
</section>

app/views/motivos/index.html.erb
<section class="content-header">
    <%= link_to "Adicionar Motivo", new_motivo_path, class: "btn btn-primary btn-lg "%>
        <div class="box-produtos">
            <div class="box-header">
                <h3 class="box-title">Motivos</h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<section class="content">
    <!-- /.box-header -->
    <div class="box box-body table-responsive no-padding">
        <table class="table table-hover">
            <tr>
                <th>ID</th>
                <th>Descrição</th>
            </tr>

            <% @motivos.each do |motivo| %>
                <%if current_user == motivo.user %>
                    <tr>
                        <td>
                            <%= motivo.id %>
                        </td>
                        <td>
                            <%= motivo.descricao %>
                        </td>
                        <td>
                            <%= link_to 'Visualizar'%>
                        </td>
                        <td>
                            <%= link_to 'Alterar', edit_motivo_path(motivo.id)%>
                        </td>
                        <td>
                            <%= link_to 'Excluir', motivo, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                    <%end%>
                        <%end%>
        </table>

        <!-- /.box-body -->
    </div>
</section>

app/views/motivos/new.html.erb
<section class="content-header">
    <h1>Novo Motivo</h1>
    <ol class="breadcrumb">
        <a class="btn btn-app" href="<%= motivos_index_path %>">
            <i class="fa fa-reply"></i> Voltar
        </a>
    </ol>
</section>
<section class="content">
    <div class="container">
        <%= render "form" %>
    </div>
</section>

app/views/motivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @motivo.descricao %>
</p>

<%= link_to 'Edit', edit_motivo_path(@motivo) %> |
<%= link_to 'Back', motivos_path %>