config/routes.rb
Rails.application.routes.draw do

  root to: "inicio#index"
   get "login", to: "login#new"
   post "login", to: "login#create"
   get "newinteressado", to: "users#newinteressado"
   get "newestudante", to: "users#newestudante"
   get "newinvestidor", to: "users#newinvestidor"
   get "newcompany", to: "users#newcompany"
   resources :users, only: [:newcompany, :create] 
   resources :categories, only: [:new, :create, :edit, :update, :edit, :update]
   get"/categories/:id" => "categories#destroy"
   get "categorias/index", to: "categories#index"
   get "produtos/index", to: "produtos#index"
   get '/solucoes/:id', to: 'solucoes#show' , as: 'solucoe'
   resources :produtos, only: [:new, :create, :edit, :update]
   get "produtos/index", to: "produtos#index"
   get"/produtos/:id" => "produtos#destroy"
   resources :marcas, only: [:new, :create, :edit, :update]
   get "marcas/index", to: "marcas#index"
   get"/marcas/:id" => "marcas#destroy"
   get "/home", to: "home#index"
   resources :grupos, only: [:new, :create, :edit, :update, :edit, :update]
   get "grupos/index", to: "grupos#index"
   get"/grupos/:id" => "grupos#destroy"
 
   get "subgrupos/index", to: "subgrupos#index"
   resources :subgrupos, only: [:new, :create, :edit, :update]
   get"/subgrupos/:id" => "subgrupos#destroy"
   get "parceiros/index", to: "parceiros#index"
   resources :parceiros, only: [:new, :create, :edit, :update]
   get"/parceiros/:id" => "parceiros#destroy"
   get "financeiro/index", to: "financeiros#index"
   resources :financeiros, only: [:new, :create, :edit, :update]
   get"/financeiro/:id" => "financeiros#destroy"
   get "inicio", to: "inicio#index"
   get "solucoes", to: "solucoes#index"
   get "viewprodutos", to: "solucoes#produtos"
   get "palavras/index", to: "palavras_chaves#index" 
   resources :palavras_chaves, only: [:new, :create, :edit, :update]
   get "palavras_chaves/:id" => "palavras_chaves#destroy"
   get "plataformas/index", to: "plataformas#index" 
   resources :plataformas, only: [:new, :create, :edit, :update]
   get "plataformas/:id" => "plataformas#destroy"
   get "tiposprojetos/index", to: "tipo_projetos#index" 
   resources :tipo_projetos, only: [:new, :create, :edit, :update]
   get"/tipo_projetos/:id" => "tipo_projetos#destroy"
   get '/produtoschaves/:id', to: 'produto_chaves#show' , as: 'produtochaves'
    get '/produtoschaves/:produto_id', to: 'produtos#associacao' , as: 'associacao'
   resources :produto_chaves, only: [:new,  :create, :edit, :update]
 
   resources :visitantes, only: [:new, :create]
  resources :parceiro_produtos
   get "interesse/index", to: "parceiro_produtos#index"
   get "interesse/new", to: "parceiro_produtos#interesse" 
   get "interesse/adicionarinteresse", to: "parceiro_produtos#adicionarinteresse" 
   get '/interesses/:id', to: 'parceiro_produtos#produto' , as: 'interesse'
  get "visitantes/login", to: "loginvisitantes#new"
 post "visitantes/login", to: "loginvisitantes#create"
   resources :contatos
  resources :emails
   resources :visitanteinteressados
     resources :perfils, only: [:new,  :create, :edit, :update]
  resources :enderecos
    get "perfil/index", to: "perfils#index"
      get "ideia/index", to: "ideia#index" 
   get "ideia/suasideias", to: "ideia#suasideias" 
   get "ideium/:id", to: 'ideia#show', as: 'interessou'
    get "suaideia/:id", to: 'ideia#suaideiashow', as: 'suaideia'
   resources :ideia, only: [:new, :create, :edit, :update]
   get"/ideia/:id" => "ideia#destroy"
    
    resources :useradmin, only: [:new, :create, :edit, :update]
    get 'useradmin/index', to: "useradmin#index"
    resources :modulos, only: [:new, :create, :edit, :update]
    get 'modulos/index', to: "modulos#index"

  resources :motivos, only: [:new, :create, :edit, :update]
  get 'motivos/index', to: "motivos#index"
  resources :agendas, only: [:new, :create, :edit, :update]
  get 'agendas/index', to: "agendas#index"
  resources :statuses, only: [:new, :create, :edit, :update]
  
  resources :tipos, only: [:new, :create, :edit, :update]
  resources :empresas, only: [:new, :create, :edit, :update]
  get 'empresa/index', to: "empresas#index"

 

end

app/models/financeiro.rb
class Financeiro < ActiveRecord::Base
end

app/controllers/financeiros_controller.rb
class FinanceirosController < ApplicationController
   before_filter :authorize_user, only: [:show, :edit, :update, :destroy, :index]

  # GET /financeiros
  # GET /financeiros.json
  def index
     @financeiro = Financeiro.all

    respond_to do |format|
      format.html  #index.html.erb
      format.json {render json: @financeiro}
    end

  end

  # GET /financeiros/1
  # GET /financeiros/1.json
  def show
  end

  # GET /financeiros/new
  def new
    @financeiro = Financeiro.new
  end

  # GET /financeiros/1/edit
  def edit
  end

  # POST /financeiros
  # POST /financeiros.json
  def create
    @financeiro = Financeiro.new(financeiro_params)

    respond_to do |format|
      if @financeiro.save
        format.html { redirect_to financeiro_index_path, notice: 'Financeiro was successfully created.' }
        format.json { render :show, status: :created, location: @financeiro }
      else
        format.html { render :new }
        format.json { render json: @financeiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financeiros/1
  # PATCH/PUT /financeiros/1.json
  def update
    respond_to do |format|
      if @financeiro.update(financeiro_params)
        format.html { redirect_to financeiro_index_path, notice: 'Financeiro was successfully updated.' }
        format.json { render :show, status: :ok, location: @financeiro }
      else
        format.html { render :edit }
        format.json { render json: @financeiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financeiros/1
  # DELETE /financeiros/1.json
  def destroy
    @financeiro.destroy
    respond_to do |format|
      format.html { redirect_to financeiros_url, notice: 'Financeiro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financeiro
      @financeiro = Financeiro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financeiro_params
      params.require(:financeiro).permit(:parcela, :data_emissa, :data_vencimento, :valor, :data_rebimento, :valor_recebido)
    end
    def authorize_user
      unless current_user
        redirect_to root_path, alert:"You need to login to continue."
      end
    end
end

app/helpers/financeiros_helper.rb
module FinanceirosHelper
end

app/views/financeiros/_form.html.erb
<%= form_for(@financeiro) do |f| %>
  <% if @financeiro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@financeiro.errors.count, "error") %> prohibited this financeiro from being saved:</h2>

      <ul>
      <% @financeiro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parcela %><br>
    <%= f.number_field :parcela %>
  </div>
  <div class="field">
    <%= f.label :data_emissa %><br>
    <%= f.date_select :data_emissa %>
  </div>
  <div class="field">
    <%= f.label :data_vencimento %><br>
    <%= f.date_select :data_vencimento %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :data_rebimento %><br>
    <%= f.date_select :data_rebimento %>
  </div>
  <div class="field">
    <%= f.label :valor_recebido %><br>
    <%= f.text_field :valor_recebido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/financeiros/edit.html.erb
<h1>Editing Financeiro</h1>

<%= render 'form' %>

<%= link_to 'Back', financeiros_path %>

app/views/financeiros/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Adicionar Titulo", new_financeiro_path, class: "btn btn-primary btn-lg "%>
 <div class="box-produtos">
            <div class="box-header">
              <h3 class="box-title">Financeiro</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
  <thead>
    <tr>
      <th>Parcela</th>
      <th>Data emissa</th>
      <th>Data vencimento</th>
      <th>Valor</th>
      <th>Data rebimento</th>
      <th>Valor recebido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% todos = Financeiro.all  %>
      <% todos.each do |financeiro| %>
      <tr>
        <td><%= financeiro.parcela %></td>
        <td><%= financeiro.data_emissa %></td>
        <td><%= financeiro.data_vencimento %></td>
        <td><%= financeiro.valor %></td>
        <td><%= link_to 'Alterar', edit_financeiro_path(financeiro) %></td>
        <td><%= link_to 'Destroy', financeiro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>
</div>

app/views/financeiros/new.html.erb
<h1>New Financeiro</h1>

<%= render 'form' %>

<%= link_to 'Back', financeiros_path %>

app/views/financeiros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parcela:</strong>
  <%= @financeiro.parcela %>
</p>

<p>
  <strong>Data emissa:</strong>
  <%= @financeiro.data_emissa %>
</p>

<p>
  <strong>Data vencimento:</strong>
  <%= @financeiro.data_vencimento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @financeiro.valor %>
</p>

<p>
  <strong>Data rebimento:</strong>
  <%= @financeiro.data_rebimento %>
</p>

<p>
  <strong>Valor recebido:</strong>
  <%= @financeiro.valor_recebido %>
</p>

<%= link_to 'Edit', edit_financeiro_path(@financeiro) %> |
<%= link_to 'Back', financeiros_path %>