config/routes.rb
Rails.application.routes.draw do

  root to: "inicio#index"
   get "login", to: "login#new"
   post "login", to: "login#create"
   get "newinteressado", to: "users#newinteressado"
   get "newestudante", to: "users#newestudante"
   get "newinvestidor", to: "users#newinvestidor"
   get "newcompany", to: "users#newcompany"
   resources :users, only: [:newcompany, :create] 
   resources :categories, only: [:new, :create, :edit, :update, :edit, :update]
   get"/categories/:id" => "categories#destroy"
   get "categorias/index", to: "categories#index"
   get "produtos/index", to: "produtos#index"
   get '/solucoes/:id', to: 'solucoes#show' , as: 'solucoe'
   resources :produtos, only: [:new, :create, :edit, :update]
   get "produtos/index", to: "produtos#index"
   get"/produtos/:id" => "produtos#destroy"
   resources :marcas, only: [:new, :create, :edit, :update]
   get "marcas/index", to: "marcas#index"
   get"/marcas/:id" => "marcas#destroy"
   get "/home", to: "home#index"
   resources :grupos, only: [:new, :create, :edit, :update, :edit, :update]
   get "grupos/index", to: "grupos#index"
   get"/grupos/:id" => "grupos#destroy"
 
   get "subgrupos/index", to: "subgrupos#index"
   resources :subgrupos, only: [:new, :create, :edit, :update]
   get"/subgrupos/:id" => "subgrupos#destroy"
   get "parceiros/index", to: "parceiros#index"
   resources :parceiros, only: [:new, :create, :edit, :update]
   get"/parceiros/:id" => "parceiros#destroy"
   get "financeiro/index", to: "financeiros#index"
   resources :financeiros, only: [:new, :create, :edit, :update]
   get"/financeiro/:id" => "financeiros#destroy"
   get "inicio", to: "inicio#index"
   get "solucoes", to: "solucoes#index"
   get "viewprodutos", to: "solucoes#produtos"
   get "palavras/index", to: "palavras_chaves#index" 
   resources :palavras_chaves, only: [:new, :create, :edit, :update]
   get "palavras_chaves/:id" => "palavras_chaves#destroy"
   get "plataformas/index", to: "plataformas#index" 
   resources :plataformas, only: [:new, :create, :edit, :update]
   get "plataformas/:id" => "plataformas#destroy"
   get "tiposprojetos/index", to: "tipo_projetos#index" 
   resources :tipo_projetos, only: [:new, :create, :edit, :update]
   get"/tipo_projetos/:id" => "tipo_projetos#destroy"
   get '/produtoschaves/:id', to: 'produto_chaves#show' , as: 'produtochaves'
    get '/produtoschaves/:produto_id', to: 'produtos#associacao' , as: 'associacao'
   resources :produto_chaves, only: [:new,  :create, :edit, :update]
 
   resources :visitantes, only: [:new, :create]
  resources :parceiro_produtos
   get "interesse/index", to: "parceiro_produtos#index"
   get "interesse/new", to: "parceiro_produtos#interesse" 
   get "interesse/adicionarinteresse", to: "parceiro_produtos#adicionarinteresse" 
   get '/interesses/:id', to: 'parceiro_produtos#produto' , as: 'interesse'
  get "visitantes/login", to: "loginvisitantes#new"
 post "visitantes/login", to: "loginvisitantes#create"
   resources :contatos
  resources :emails
   resources :visitanteinteressados
     resources :perfils, only: [:new,  :create, :edit, :update]
  resources :enderecos
    get "perfil/index", to: "perfils#index"
      get "ideia/index", to: "ideia#index" 
   get "ideia/suasideias", to: "ideia#suasideias" 
   get "ideium/:id", to: 'ideia#show', as: 'interessou'
    get "suaideia/:id", to: 'ideia#suaideiashow', as: 'suaideia'
   resources :ideia, only: [:new, :create, :edit, :update]
   get"/ideia/:id" => "ideia#destroy"
    
    resources :useradmin, only: [:new, :create, :edit, :update]
    get 'useradmin/index', to: "useradmin#index"
    resources :modulos, only: [:new, :create, :edit, :update]
    get 'modulos/index', to: "modulos#index"

  resources :motivos, only: [:new, :create, :edit, :update]
  get 'motivos/index', to: "motivos#index"
  resources :agendas, only: [:new, :create, :edit, :update]
  get 'agendas/index', to: "agendas#index"
  resources :statuses, only: [:new, :create, :edit, :update]
  
  resources :tipos, only: [:new, :create, :edit, :update]
  resources :empresas, only: [:new, :create, :edit, :update]
  get 'empresa/index', to: "empresas#index"

 

end

app/controllers/ideia_controller.rb
class IdeiaController < ApplicationController
  before_filter :authorize_user, only: [:show, :edit, :update, :destroy, :new]

  # GET /ideia
  # GET /ideia.json
  def index
    @ideia = Ideium.paginate(page: params[:page], per_page: 5)
		
  end
 def suasideias
@ideia = current_user.ideia
  end

    def new
    @ideium = current_user.ideia.build
  end

  # GET /ideia/1
  # GET /ideia/1.json
  def show
    @ideium = Ideium.joins(:user => [:perfil]).find(params[:id])
  end
    def suaideiashow
    @ideium = Ideium.joins(:user => [:perfil]).find(params[:id])
  end


  # GET /ideia/new

  # GET /ideia/1/edit
  def edit
    @ideium = current_user.ideia.find(params[:id])
    @ideium = Ideium.joins(:user => [:perfil]).find(params[:id])
  end

  # POST /ideia
  # POST /ideia.json
  def create
    @ideium = current_user.ideia.build(ideium_params)

    respond_to do |format|
      if @ideium.save
        format.html { redirect_to suaideia_path(@ideium), notice: 'Ideium was successfully created.' }
        format.json { render :show, status: :created, location: @ideium }
      else
        format.html { render :new }
        format.json { render json: @ideium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideia/1
  # PATCH/PUT /ideia/1.json
  def update

     @ideium = current_user.ideia.find(params[:id])
    respond_to do |format|
      if @ideium.update(ideium_params)
        format.html { redirect_to ideia_index_path, notice: 'Ideium was successfully updated.' }
        format.json { render :show, status: :ok, location: @ideium }
      else
        format.html { render :edit }
        format.json { render json: @ideium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideia/1
  # DELETE /ideia/1.json
  def destroy
     @ideium = current_user.ideia.find(params[:id])
    @ideium.destroy
    respond_to do |format|
      format.html { redirect_to ideia_index_path, notice: 'Ideium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ideium
      @ideium = Ideium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ideium_params
      params.require(:ideium).permit(:descricao, :descricaocompleta, :descricaoum, :descricaodois, :descricaotres, :tituloum, :titulodois, :titulotres)
    end
      def authorize_user
      unless current_user
        redirect_to root_path, alert:"You need to login to continue."
      end
    end

end

app/helpers/ideia_helper.rb
module IdeiaHelper
end

app/views/ideia/_form.html.erb
<%= form_for(@ideium, html: { class: 'form-horizontal' }) do |f| %>
    <div class="row">
        <% if @ideium.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@ideium.errors.count, "error") %> prohibited this ideium from being saved:</h2>

                <ul>
                    <% @ideium.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
            <% end %>


                <section class="content">


                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <h2 class="section-heading">
                                Descrição Principal <br>
                                <%= f.text_field :descricao %>
                            </h2>
                            <h3 class="section-subheading text-muted">
                                Descrição Detalhada<br>
                                <%= f.text_area :descricaocompleta %>
                            </h3>
                        </div>
                    </div>
                    <div class="row text-center">
                        <div class="col-md-4">
                            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                    </span>
                            <h4 class="service-heading">
                                <%= f.text_field :tituloum %>
                            </h4>
                            <p class="text-muted">
                                <%= f.text_area :descricaoum %>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                    </span>
                            <h4 class="service-heading">
                                <%= f.text_field :titulodois %>
                            </h4>
                            <p class="text-muted">
                                <%= f.text_area :descricaodois %>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                            <h4 class="service-heading">
                                <%= f.text_field :titulotres %>
                            </h4>
                            <p class="text-muted">
                                <%= f.text_area :descricaotres %>
                            </p>
                        </div>
                        <div class="control-group controls">
                            <%= f.submit %>
                        </div>
                    </div>
                </section>
                <% end %>
                    <section class="success " id="about ">

                        <div class="row ">
                            <div class="col-lg-12 text-center ">
                                <h2>Um Pouco de
                                    <%= @ideium.user.name %>
                                </h2>
                                <hr class="star-light ">
                                <div class="alterarideia">
                                    <a class="btn btn-app" href="<%= edit_perfil_path(@ideium.user.perfil.id) %>">
                                        <i class="fa fa-edit"></i> Alterar
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row ">
                            <div class="col-lg-4 col-lg-offset-2 ">
                                <p>
                                    Profissão:
                                    <%= @ideium.user.perfil.profissao %><br> Formação:
                                        <%= @ideium.user.perfil.formacao %><br> Conhecimentos:
                                            <%= @ideium.user.perfil.conhecimentos %>

                                </p>
                            </div>
                            <div class="col-lg-4 ">
                                <p>
                                    Habilidades:
                                    <%= @ideium.user.perfil.habilidades %> <br> Objetivos:
                                        <%= @ideium.user.perfil.objetivo %> <br>


                                </p>

                            </div>
                            <div class="col-lg-8 col-lg-offset-2 text-center ">
                                <a href="# " class="btn btn-lg btn-outline ">
                                    <i class="fa fa-download "></i> Download Theme
                                </a>
                            </div>
                        </div>

                    </section>

app/views/ideia/edit.html.erb
<section class="content-header">
    <h1>Alterar Ideia
    </h1>
    <ol class="breadcrumb">
        <a class="btn btn-app" href="<%= ideia_index_path %>">
            <i class="fa fa-reply"></i> Voltar
        </a>
    </ol>
</section>
<section class="content">

    <%= render "form" %>

</section>

app/views/ideia/index.html.erb
<!-- Header -->
<section class="ideia" style="text-align: center;">
    <section class="content">





        <div class="row">

            <div class="col-xs-6 col-sm-3 sidebar-offcanvas menuideia" style="float: right;">
                <div class="list-group">
                    <a href="paginas/empreededorismo.html" class="list-group-item">Necessidades de Mercado</a>
                    <a href="paginas/empreededorismo.html" class="list-group-item">Freelances</a>
                    <a href="paginas/governo.html" class="list-group-item">Empreededorismo</a>
                    <a href="paginas/bolsadevalores.html" class="list-group-item">Bolsa de Valores</a>
                    <a href="paginas/cursosgratuitos.html" class="list-group-item">Cursos Gratuitos</a>
                    <a href="paginas/concursos.html" class="list-group-item">Governo</a>
                    <a href="paginas/prrofissoes.html" class="list-group-item">Profissões</a>
                    <a href="paginas/noticiasdomundo.html" class="list-group-item">Noticias do Mundo</a>
                    <a href="paginas/brasil.html" class="list-group-item">Brasil</a>
                    <a href="paginas/mercadodetrabalho.html" class="list-group-item">Mercado de Trabalho</a>

                </div>
            </div>
            <% @ideia.each do |ideia| %>
                <%if current_user != ideia.user %>
                    <div class="col-md-7" style="float: left;">
                        <h3>
                            <%= ideia.descricao%>
                        </h3>
                        <h4>Subheading</h4>
                        <p class="lead">

                            <%= ideia.descricaocompleta%>

                        </p>

                        <a class="btn btn-primary" <%=link_to 'Interessou à Ideia', interessou_path(ideia) %></a>
                        <hr class="section-heading-spacer"></hr>
                    </div>


                    <%end%>


                        <%end%>
                            <div class="col-md-5">


                            </div>

        </div>
        <%= will_paginate @ideia, class: 'paginacao' %>


    </section>
</section>

<!-- /.container -->

app/views/ideia/new.html.erb
<section class="content-header">
    <h1>Nova Ideia
    </h1>
    <ol class="breadcrumb">
        <a class="btn btn-app" href="<%= ideia_index_path %>">
            <i class="fa fa-reply"></i> Voltar
        </a>
    </ol>
</section>
<section class="content">

    <%= render "form" %>

</section>

app/views/ideia/suaideiashow.html.erb
<header>

    <div class="row">
        <div class="alterarideia">
            <a class="btn btn-app" href="<%= edit_ideium_path(@ideium.id) %>">
                <i class="fa fa-edit"></i> Alterar
            </a>
        </div>
        <div class="col-lg-12">
            <img class="img-responsive" src="/assets/profile.png" alt="">
            <div class="intro-text">
                <h1 class="name">
                    <%= @ideium.descricao %>
                </h1>
                <hr class="star-light">
                <span class="skills"><%= @ideium.user.name %> - <%= @ideium.user.perfil.profissao %>  - <%= @ideium.user.perfil.descricao %> </span>
            </div>
        </div>
    </div>

</header>
<section class="content">


    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">
                <%= @ideium.descricao %>
            </h2>
            <h3 class="section-subheading text-muted">
                <%= @ideium.descricaocompleta %>
            </h3>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-4">
            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                    </span>
            <h4 class="service-heading">
                <%= @ideium.tituloum %>
            </h4>
            <p class="text-muted">
                <%= @ideium.descricaoum %>
            </p>
        </div>
        <div class="col-md-4">
            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                    </span>
            <h4 class="service-heading">
                <%= @ideium.titulodois%>
            </h4>
            <p class="text-muted">
                <%= @ideium.descricaodois %>
            </p>
        </div>
        <div class="col-md-4">
            <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
            <h4 class="service-heading">
                <%= @ideium.titulotres %>
            </h4>
            <p class="text-muted">
                <%= @ideium.descricaotres %>
            </p>
        </div>

    </div>
</section>
<!-- Portfolio Grid Section -->
<section class="content">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Portfolio</h2>
            <hr class="star-primary">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 portfolio-item">
            <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                <div class="caption">
                    <div class="caption-content">
                        <i class="fa fa-search-plus fa-3x"></i>
                    </div>
                </div>
                <img src="/assets/cabin.png" class="img-responsive" alt="Cabin">
            </a>
        </div>
        <div class="col-sm-4 portfolio-item">
            <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                <div class="caption">
                    <div class="caption-content">
                        <i class="fa fa-search-plus fa-3x"></i>
                    </div>
                </div>
                <img src="/assets/cake.png" class="img-responsive" alt="Slice of cake">
            </a>
        </div>
        <div class="col-sm-4 portfolio-item">
            <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                <div class="caption">
                    <div class="caption-content">
                        <i class="fa fa-search-plus fa-3x"></i>
                    </div>
                </div>
                <img src="/assets/circus.png" class="img-responsive" alt="Circus tent">
            </a>
        </div>
        <div class="col-sm-4 portfolio-item">
            <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                <div class="caption">
                    <div class="caption-content">
                        <i class="fa fa-search-plus fa-3x"></i>
                    </div>
                </div>
                <img src="/assets/game.png " class="img-responsive " alt="Game controller ">
            </a>
        </div>
        <div class="col-sm-4 portfolio-item ">
            <a href="#portfolioModal5 " class="portfolio-link " data-toggle="modal ">
                <div class="caption ">
                    <div class="caption-content ">
                        <i class="fa fa-search-plus fa-3x "></i>
                    </div>
                </div>
                <img src="/assets/safe.png " class="img-responsive " alt="Safe ">
            </a>
        </div>
        <div class="col-sm-4 portfolio-item ">
            <a href="#portfolioModal6 " class="portfolio-link " data-toggle="modal ">
                <div class="caption ">
                    <div class="caption-content ">
                        <i class="fa fa-search-plus fa-3x "></i>
                    </div>
                </div>
                <img src="/assets/submarine.png " class="img-responsive " alt="Submarine ">
            </a>
        </div>
    </div>

</section>

<!-- About Section -->
<section class="success " id="about ">

    <div class="row ">
        <div class="col-lg-12 text-center ">
            <h2>Um Pouco de
                <%= @ideium.user.name %>
            </h2>
            <hr class="star-light ">
        </div>
    </div>
    <div class="row ">
        <div class="col-lg-4 col-lg-offset-2 ">
            <p>
                Profissão:
                <%= @ideium.user.perfil.profissao %><br> Formação:
                    <%= @ideium.user.perfil.formacao %><br> Conhecimentos:
                        <%= @ideium.user.perfil.conhecimentos %>

            </p>
        </div>
        <div class="col-lg-4 ">
            <p>
                Habilidades:
                <%= @ideium.user.perfil.habilidades %> <br> Objetivos:
                    <%= @ideium.user.perfil.objetivo %> <br>


            </p>

        </div>
        <div class="col-lg-8 col-lg-offset-2 text-center ">
            <a href="# " class="btn btn-lg btn-outline ">
                <i class="fa fa-download "></i> Download Theme
            </a>
        </div>
    </div>

</section>

<!-- Contact Section -->
<section id="contact ">

    <div class="row ">
        <div class="col-lg-12 text-center ">
            <h2>Contact Me</h2>
            <hr class="star-primary ">
        </div>
    </div>
    <div class="row ">
        <div class="col-lg-8 col-lg-offset-2 ">
            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
            <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
            <form name="sentMessage " id="contactForm " novalidate>
                <div class="row control-group ">
                    <div class="form-group col-xs-12 floating-label-form-group controls ">
                        <label for="name ">Name</label>
                        <input type="text " class="form-control " placeholder="Name " id="name " required data-validation-required-message="Please enter your name. ">
                        <p class="help-block text-danger "></p>
                    </div>
                </div>
                <div class="row control-group ">
                    <div class="form-group col-xs-12 floating-label-form-group controls ">
                        <label for="email ">Email Address</label>
                        <input type="email " class="form-control " placeholder="Email Address " id="email " required data-validation-required-message="Please enter your email address. ">
                        <p class="help-block text-danger "></p>
                    </div>
                </div>
                <div class="row control-group ">
                    <div class="form-group col-xs-12 floating-label-form-group controls ">
                        <label for="phone ">Phone Number</label>
                        <input type="tel " class="form-control " placeholder="Phone Number " id="phone " required data-validation-required-message="Please enter your phone number. ">
                        <p class="help-block text-danger "></p>
                    </div>
                </div>
                <div class="row control-group ">
                    <div class="form-group col-xs-12 floating-label-form-group controls ">
                        <label for="message ">Message</label>
                        <textarea rows="5 " class="form-control " placeholder="Message " id="message " required data-validation-required-message="Please enter a message. "></textarea>
                        <p class="help-block text-danger "></p>
                    </div>
                </div>
                <br>
                <div id="success "></div>
                <div class="row ">
                    <div class="form-group col-xs-12 ">
                        <button type="submit " class="btn btn-success btn-lg ">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

app/views/ideia/suasideias.html.erb
<section class="content-header">
    <%= link_to "Adicionar uma Ideia", new_ideium_path, class: "btn btn-primary btn-lg "%>
        <div class="box-produtos">
            <div class="box-header">
                <h3 class="box-title">Idéias</h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</section>
<div class="container">
    <!-- /.box-header -->
    <div class="box box-body table-responsive no-padding">
        <table class="table table-hover">
            <tr>
                <th>ID</th>
                <th>Descrição</th>
            </tr>

            <% @ideia.each do |ideia| %>
                <%if current_user == ideia.user %>
                    <tr>
                        <td>
                            <%= ideia.id %>
                        </td>
                        <td>
                            <%= ideia.descricao %>
                        </td>
                        <td>
                            <%= link_to 'Visualizar', suaideia_path(ideia) %>
                        </td>
                        <td>
                            <%= link_to 'Alterar', edit_ideium_path(ideia.id)%>
                        </td>
                        <td>
                            <%= link_to 'Excluir', ideia, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                    <%end%>
                        <%end%>
        </table>

        <!-- /.box-body -->
    </div>
</div>